Web UI "stats summary" page - a nicer error message when missing data
As per external report:

File "/postgres/pgwatch2-master/webpy/web.py", line 264, in stats_summary
data = pgwatch2_influx.get_db_overview(dbname)
File "/postgres/pgwatch2-master/webpy/pgwatch2_influx.py", line 114, in get_db_overview
data['TPS'] = exec_for_time_pairs(tps, dbname, time_pairs)
File "/postgres/pgwatch2-master/webpy/pgwatch2_influx.py", line 100, in exec_for_time_pairs
sum += values[1]
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'